// movies.js — versión corregida compatible con index.html

const sampleTrailer = "https://www.w3schools.com/html/mov_bbb.mp4"; // Tráiler genérico temporal

const MOVIES = [
  {
    id: "spiderman-into-the-spiderverse",
    title: "Spiderman: Un Nuevo Universo",
    year: 2018,
    duration: "1h 56min",
    rating: "PG",
    genres: ["Animación", "Aventura"],
    description: "Miles Morales se convierte en Spider-Man y conoce a otros héroes arácnidos de universos paralelos.",
    trailerUrl: "trailers/into-the-spiderverse.mp4",
    image: "images/spiderman-into-the-spiderverse.webp",
    post : "posters/into-the-spiderverse.webp",
    movie: "https://drive.google.com/file/d/1Gp-v1xvRausPDh9c88yxOSFusXM9dkwE/preview"
  },
  {
    id: "spiderman2-across-the-spiderverse",
    title: "Spider-Man 2: A través del Spiderverso",
    year: 2023,
    duration: "2h 20min 05s",
    rating: "PG",
    genres: ["Animación", "Acción", "Aventura", "Superhéroes"],
    description: "Después de reunirse con Gwen Stacy, el amigable vecino de tiempo completo de Brooklyn Spiderman, es lanzado a través del multiverso, donde se encuentra a un equipo de gente araña encomendada con proteger su mera existencia.",
    image: "images/spiderman2-across-the-spiderverse.webp",
    post: "posters/spiderman2-across-the-spiderverse.webp",
    trailerUrl: "trailers/across-the-spiderverse(2).mp4",
    movie: "https://drive.google.com/file/d/11SMv4hmFUM71MWcPYm5qXf5j-tJgeAWp/preview"
  },
  {
    id: "spiderman3-beyond-into-the-spiderverse",
    title: "Spider-Man 3 Proximamente[2027]: Beyond into the spiderverse",
    year: 2027,
    duration: "2h 20min 05s",
    rating: "PG",
    genres: ["Animación", "Acción", "Aventura", "Superhéroes"],
    description: "[Próximamente]",
    image: "images/beyond-the-spiderverse.jpg",
    post: "https://m.media-amazon.com/images/M/MV5BMjQwZWExNzAtOTEzZC00NTI3LTk1MDctYjQ1M2M1MzQ5YzljXkEyXkFqcGc@._V1_.jpg",
    trailerUrl: "IJ3o8oX1nyjbsyfpDwkH-cS/preview",
    movie: "https://drive.google.com/file/d/11SMv4hmFUM71MWcPYm5qXf5j-tJgeAWp/preview"
  },
  {
    id: "face-off",
    title: "Contracara",
    year: 1997,
    duration: "2h 18min 57s",
    rating: "R",
    genres: ["Acción", "Thriller", "Crimen"],
    description:  "Un agente del FBI se somete a una cirugía experimental para asumir la identidad del terrorista que mató a su hijo. Pero las cosas salen terriblemente mal.",
    trailerUrl: "7tp_UB4jTKujqn/preview",
    image: "https://m.media-amazon.com/images/S/pv-target-images/c2668312b9f29fb8e5780ddcb9a183831f4acc01347c3b704e098f48477df639.jpg",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/0cbfc5e5-71fe-4605-99fc-1ae7f66d2dc0/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1FsEqOKWlq4zMSeYOF-7tp_UB4jTKujqn/preview"
  },
  {
    id: "interestellar",
    title: "Interestelar",
    year: 2014,
    duration: "2h 49min",
    rating: "PG-13",
    genres: ["Ciencia ficción", "Drama", "Aventura"],
    description:  "Un grupo de astronautas viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad mientras la Tierra agoniza.",
    trailerUrl: "trailers/interestellar.mp4",
    image: "images/interestellar.webp",
    post: "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/aa5b9295-8f9c-44f5-809b-3f2b84badfbf/8a7dd34b09c9c25336a3d850d4c431455e1aaaf0.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom",
    movie: "https://drive.google.com/file/d/1cVVPgzsRjlombZxDsP2YWa9F9cHs0xa7/preview"
  },
  {
    id: "karatekid-1984",
    title: "Karate Kid (1984)",
    year: 1984,
    duration: "2h 6min",
    rating: "PG",
    genres: ["Drama", "Deportes", "Inspiradora"],
    description:
      "Daniel se muda a California y sufre acoso hasta que un sabio maestro de karate, el Sr. Miyagi, le enseña el arte del equilibrio y la disciplina.",
    trailerUrl: "cLsXWXQFHsCA26jYspc5/preview",
    image: "https://m.media-amazon.com/images/S/pv-target-images/8525873a8c8da460d36c6230856d1080c6a995670b1e15100fd796d18d56bc3e.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/36c87917428a50fdbb5d7481433ddbddf544083e8d6d2b141ec61e84f5a5448c.jpg",
    movie: "https://drive.google.com/file/d/1vytWPJ8SuHa5cLsXWXQFHsCA26jYspc5/preview"
  },
  {
    id: "karate-kid-legends",
    title: "Karate Kid Leyendas",
    year: 2025,
    duration: "1h 34min",
    rating: "PG",
    genres: ["Infantil","Acción"],
    description:"Tras mudarse a Nueva York, el prodigio del kung fu Li Fong atrae una atención no deseada y se embarca en un viaje para participar en la competición de karate definitiva. Li fusiona sus estilos únicos para prepararse para un épico enfrentamiento.",
    trailerUrl: "trailers/karate-kid-legends.mp4",
    image: "https://m.media-amazon.com/images/S/pv-target-images/d57b76d7175a17c471fbabccf92ccd3fed7d53bfd4b35a41a76c9b64d81d5a33.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/44a88afaadb493bb565c0d418474ff016be1cdaf443448a37c44e345af79e265._UR1920,1080_.png",
    movie: "https://drive.google.com/file/d/1A26SVMjdf0MWh_HmFkXG_qtOv_C4lYK2/preview"
  },
  {
    id: "laleyendade-loschaneques",
    title: "La Leyenda de los Chaneques",
    year: 2023,
    duration: "1h 25min",
    rating: "A",
    genres: ["Animación", "Fantasía", "Aventura"],
    description: "Cinco años después de haber renunciado a sus poderes, Leo San Juan se encuentra en Veracruz acompañando a Nando cuando una antigua maldición local regresa. Esta vez, Leo no tiene poderes, no tiene amigos, tiempo y, al parecer… tampoco oportunidad.",
    trailerUrl: "trailers/la-leyenda-de-los-chaneques.mp4",
    image: "https://m.media-amazon.com/images/S/pv-target-images/1640bf4852cbd0ae978d1277489dc5849a7c1455ba9f5edcfaa60f631ae58bef.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/234088d196d0e848255707bf370ce9bfec12e57d2c77d1e5bc9dcacf001b5108.jpg",
    movie: "https://drive.google.com/file/d/1j2-DvVDho1-u6DoJhZpr3fG6mpyAMGL5/preview"
  },
  {
    id: "venom3",
    title: "Venom 3: The Last Dance",
    year: 2024,
    duration: "2h 0min",
    rating: "PG-13",
    genres: ["Acción", "Ciencia ficción"],
    description: "Eddie y Venom están huyendo. Perseguidos por sus dos mundos y con la red cerrándose, el dúo se ve obligado a tomar una decisión devastadora que echará el telón al último baile de Venom y Eddie.",
    trailerUrl: "trailers/venom-3.mp4",
    image: "https://m.media-amazon.com/images/S/pv-target-images/c2d6430ada2a73209fc05ff1e79cd3dfdf46c92326bed76262d40bd5033e2bb4.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/b6ecdea0a5f796ac6716aac314cd15b49bfd5efcb863aecaac91ef12a0fe3625.jpg",
    movie: "https://drive.google.com/file/d/1-I98WaJ_C622i2YMeBFjcEn43808KgmR/preview"
  },
  {
    id: "clockstoppers",
    title: "Tiempo Congelado",
    year: 2002,
    duration: "1h 55min",
    rating: "PG-13",
    genres: ["Suspenso", "Drama", "Ciencia ficción"],
    description: "Un adolescente y su amigo deben salvar a su padre de un hombre que ha pedido la construcción de dispositivo de tiempo.",
    trailerUrl: "_i5endV/preview",
    image: "https://m.media-amazon.com/images/M/MV5BYzhmZTExNjktYWNmYS00YzdmLTllZjktYTU5M2ViMDk1MTU4XkEyXkFqcGc@._V1_.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/498665c87a32081ff493eb39995ff60e6c42705eb9c3fc54fbca741099a7f2bd.jpg",
    movie: "https://drive.google.com/file/d/1mi8Ltlqx01KVDLKIIQXL0l05A_i5endV/preview"
  },
  {
    id: "lightyear",
    title: "Lightyear",
    year: 2022,
    duration: "1h 45min",
    rating: "PG",
    genres: ["Animación", "Aventura"],
    description: "Buzz Lightyear se embarca en una aventura intergaláctica con un grupo de reclutas ambiciosos y su compañero robot. Los amigos tendrán que aprender a trabajar juntos para escapar del malvado Zurg y su ejército de robots.",
    trailerUrl: "trailers/lightyear.mp4",
    image: "https://m.media-amazon.com/images/I/71EgLo5pqnL._AC_UF894,1000_QL80_.jpg",
    post: "https://cdn.bolivia.com/sdi/2022/07/21/lightyear-fecha-estreno-chris-evans-disney-plus-1050224.jpg",
    movie: "https://drive.google.com/file/d/1m5gLKdgBV2loj5qCDIgLakOnUS7SN5T4/preview"
  },
  {
    id: "mufasa",
    title: "Mufasa - El Rey León",
    year: 2024,
    duration: "1h 58min",
    rating: "PG-13",
    genres: ["Aventura","Musical"],
    description:"Una inundación separa al cachorro Mufasa de sus padres, pero el rey de los leones lo acoge como a uno de los suyos tras demostrar su valentía.Al crecer, una manada de leones desterrados y los celos de su hermano adoptivo lo pondrán en peligro.",
    trailerUrl: "trailers/mufasa.mp4",
    image: "https://images.justwatch.com/poster/326095284/s718/mufasa-el-rey-leon.jpg",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/018ffc14-acb8-44c6-82c7-3c4dd3091c3f/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1kpAxZOwLmSTcZZnHZ_vDlfNHqv9ZtGgz/preview"
  },
  {
    id: "how-train-your-dragon",
    title: "Cómo Entrenar a tu Dragón : Próximamente",
    year: 2014,
    duration: "1h 42min",
    rating: "PG",
    genres: ["Animación","Aventura","Infantil","Acción"],
    description:"Hipo, un adolescente vikingo inadaptado ve la oportunidad de cambiar el curso del futuro de su clan cuando se hace amigo de un dragón herido.",
    trailerUrl: "trailers/dragon.mp4",
    image: "images/dragon.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/2216969f4080744c6652d39f24f3889577623e22dbb36656145b4c2d4939a107.jpg",
    movie: ""
  },
  {
    id: "how-train-your-dragon-2",
    title: "Cómo Entrenar a tu Dragón 2",
    year: 2014,
    duration: "1h 42min",
    rating: "PG",
    genres: ["Animación","Aventura","Infantil","Acción"],
    description:"Cinco años después de la paz en Berk, Hipo y Desdentao exploran nuevas tierras donde descubren una cueva de hielo con cientos de dragones salvajes y a una misteriosa jinete llamada Valka. Pronto se dan cuenta de que Valka, su madre que se creía muerta, protege a los dragones de un cazador llamado Eret, y que este trabaja para Drago Puño Sangrientor, un villano que quiere esclavizar a todos los dragones para su ejército. Berk se ve amenazada por Drago y su dragón alfa, lo que lleva a una batalla épica en la que Hipo, con la ayuda de su madre y Valka, debe detenerlo y asegurar la paz para siempre.",
    trailerUrl: "trailers/dragon2.mp4",
    image: "https://m.media-amazon.com/images/S/pv-target-images/23015dc809dd71e28155b18cc36279bb1874028facfc0419c23a1505e198970b.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/d58b307c15c88f7018175db9c3f91476d73f2bd82956cc099be1ee1a4099ca41.jpg",
    movie: "https://drive.google.com/file/d/1HoxHuCgIgetLZk6nuFE6nN9a_1YK9Py_/preview"
  },
  {
    id: "how-train-your-dragon-3",
    title: "Cómo Entrenar a tu Dragón 3",
    year: 2019,
    duration: "1h 44min",
    rating: "PG",
    genres: ["Animación","Aventura","Infantil","Acción"],
    description: "Hipo y Chimuelo enfrentando una nueva amenaza en forma de un cazador de dragones llamado Grimmel, que quiere capturar a Desdentado. Mientras tanto, el descubrimiento de una Furia Luminosa, una dragona salvaje, pone a prueba la relación entre Hipo y Chimuelo.",
    trailerUrl: "trailers/dragon3.mp4",
    image: "https://m.media-amazon.com/images/S/pv-target-images/daf0864124d5b8b8bf1881a9b0b9e577b3ea10d8af5ec1ffb8e46c5a290d745c.jpg",
    post: "https://criticinema.com/wp-content/uploads/2019/02/C%C3%B3mo-entrenar-a-tu-drag%C3%B3n-3-cover-1024x436.jpg",
    movie: "https://drive.google.com/file/d/1x4CYvRvkriWKcL2aE0nqOJY1tPAq71I2/preview"
  },
  { id: "avatar-2009",
    title: "Avatar",
    year: 2009,
    duration: "2h 42min",
    rating: "PG-13",
    genres: ["Ciencia ficción", "Aventura"],
    description: "En un exuberante planeta llamado Pandora viven los Na'vi, seres que aparentan ser primitivos pero que en realidad son muy evolucionados. Debido a que el ambiente de Pandora es venenoso, los híbridos humanos/Na'vi, llamados Avatares, están relacionados con las mentes humanas, lo que les permite moverse libremente por Pandora. Jake Sully, un exinfante de marina paralítico se transforma a través de un Avatar, y se enamora de una mujer Na'vi..",
    trailerUrl: sampleTrailer,
    image: "images/avatar.jpeg",
    post: "https://spoilertown.com/wp-content/uploads/2024/07/avatar-2009.webp",
    movie: "https://drive.google.com/file/d/16JSSJ3zfvpZGG7zNGXqZ2DicCFyqrfGU/preview"
  },
  {
    id: "avatar2-elcaminodelagua",
    title: "Avatar 2 - El Camino del Agua",
    year: 2022,
    duration: "3h 12min",
    rating: "PG-13",
    genres: ["Ciencia ficción", "Aventura"],
    description: "Jake Sully y Neytiri se ven obligados a huir de su hogar debido al regreso de la RDA humana, quienes buscan colonizar Pandora y explotar sus recursos. La familia Sully busca refugio con el clan Metkayina, adaptándose a un nuevo entorno acuático y enfrentándose a un resucitado coronel Quarich, ahora en un cuerpo avatar y buscando venganza.",
    trailerUrl: "trailers/avatar2-elcaminodelagua.mp4",
    image: "images/avatar2.jpeg",
    post: "https://media.gq.com.mx/photos/639b5e4d8a20ef7d5f5a8c05/16:9/w_2560%2Cc_limit/Avatar%25202-GQ3.jpg",
    movie: "https://drive.google.com/file/d/12RRSn0kLKUea3RbJlg32Z7zLZE7v__B5/preview"
  },
  {
    id: "avatar3-fireandash",
    title: "Avatar 3 Próximamente (2026) - Fuego y Cenizas",
    year: 2026,
    duration: "3h 12min",
    rating: "PG-13",
    genres: ["Ciencia ficción", "Aventura"],
    description:"Avatar 3: Fuego y cenizas trata de la familia Sully lidiando con el duelo por la muerte de Neteyam, enfrentando una nueva amenaza: un clan Na'vi más agresivo conocido como el Pueblo de Ceniza, liderado por Varang. Esta nueva tribu, que ha rechazado a Eywa y está dispuesta a usar la violencia, podría aliarse con el Coronel Quaritch, intensificando un conflicto que amenaza con destruir Pandora.",
    trailerUrl: "trailers/avatar3-fireandash.mp4",
    image: "images/avatar3-fireandash.webp",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/41ae7704-8740-4eb8-bb01-e4285e3b9011/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: ""
  },
  {
    id: "flow",
    title: "Flow",
    year: 2024,
    duration: "1h 25min",
    rating: "PG",
    genres: ["Animación", "Drama"],
    description: "Un gato debe aprender a convivir con otros animales en un barco que flota sobre un mundo inundado.",
    trailerUrl: "trailers/flow.mp4",
    image: "https://m.media-amazon.com/images/S/pv-target-images/6cc5f6739b1bf93cc4a740df55f5fbc40211fe9303b91f1ab68311bd68265c73.png",
    post: "https://m.media-amazon.com/images/S/pv-target-images/3d4f0a9dc2fd8e0dcbca256e5dc08e32f9c3bf8b560a1171ae7bcbea7814b7f3.jpg",
    movie: "https://drive.google.com/file/d/1VVd1JCyxkHXGpsYr-3-SaD68pijn1XFS/preview"
  },
  {
    id: "get-out",
    title: "Huye",
    year: 2017,
    duration: "1h 44min",
    rating: "R",
    genres: ["Terror", "Suspenso"],
    description: "Chris va a conocer a los padres de Rose, su novia. Al principio se muestran encantadores, si bien un tanto nerviosos. Chris supone que se debe a que él es negro, pero un poco más tarde descubre que sus suegros ocultan un secreto espeluznante.",
    trailerUrl: "trailers/get-out.mp4",
    image: "https://m.media-amazon.com/images/M/MV5BM2E0MGQ2N2MtYjVkOS00MDZmLTkzZGUtN2FjYTk4MDdiYzc1XkEyXkFqcGc@._V1_.jpg",
    post: "https://pegadoalabutaca.com/wp-content/uploads/2017/05/huye.png?w=816",
    movie: "https://drive.google.com/file/d/1en6HYU4w0GfvSf3PT8ZAqcxzbHvCcjHB/preview"
  },
  {
    id: "rango",
    title: "Rango",
    year: 2011,
    duration: "1h 47min",
    rating: "PG",
    genres: ["Animación", "Aventura", "Comedia"],
    description: "Rango es un camaleón doméstico que, tras caer accidentalmente a la carretera, llega al pueblo de Dirt en el desierto de Mojave. Allí, decide hacerse pasar por un héroe legendario para ganarse la admiración de sus habitantes y se convierte en el nuevo sheriff. Sin embargo, debe enfrentarse a la crisis de agua del pueblo y descubrir al responsable para no ser desenmascarado como un farsante.",
    trailerUrl: "trailers/rango.mp4",
    image: "images/rango.webp",
    post: "https://i.blogs.es/af279b/rango-2011-johnny-depp-gore-verbinski/450_1000.jpg",
    movie: "https://drive.google.com/file/d/1SB357lg3QIGL5RvdfrJQ53_1jmnHNv7u/preview"
  },
  {
    id: "kpop-hunters",
    title: "",
    year: 2025,
    duration: "1h 36min",
    rating: "PG-13",
    genres: ["Acción", "Músical"],
    description: "Cuando no están llenando estadios, las superestrellas del k-pop Rumi, Mira y Zoey usan sus superpoderes secretos para proteger a sus fans de Gwi-Ma y los demonios.",
    trailerUrl: sampleTrailer,
    image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTnhJm-1TfFrjrNNCmN3DAmNNMsnS7RqlKT8J6MkoOvZwF9Zw_q",
    post: "https://sm.ign.com/ign_latam/gallery/k/kpop-demon/kpop-demon-hunters-gallery_9frv.jpg",
    movie: "https://drive.google.com/file/u/0/d/1yn5s7n8Cf3hnMtJdND3xG6gMq0DO3kfO/preview"
  },
  {
    id: "fast-and-furious5",
    title: "Rápidos y Furiosos 5",
    year: 2011,
    duration: "2h 10min",
    rating: "PG-13",
    genres: ["Acción", "Crimen"],
    description: "Dominic Toretto, Brian O'Conner y Mia Toretto se esconden en Río de Janeiro y se unen a un equipo para robar $100 millones del corrupto empresario Hernán Reyes. Mientras planean el atraco, son perseguidos por el agente del Servicio de Seguridad Diplomática (DSS), Luke Hobbs.",
    trailerUrl: sampleTrailer,
    image: "https://es.web.img3.acsta.net/medias/nmedia/18/83/53/62/19695928.jpg",
    post: "https://i.blogs.es/8d7a59/fast-five-1200-1200-675-675-crop-000000/450_1000.jpg",
    movie: "https://drive.google.com/file/d/1kkdCZcm_ynd7URwOML6jWAabSMSvArha/preview"
  },
  {
    id: "miraculous-world1",
    title: "Miraculous World Nueva York: Héroes Unidos",
    year: 2020,
    duration: "1h 03min",
    rating: "TV-G",
    genres: ["Animación", "Aventura","Infantil"],
    description:"Con motivo de la semana de la amistad franco-estadounidense, Marinette y su clase viajan a Nueva York: la ciudad de los superhéroes. Es la oportunidad para que Marinette pase tiempo con sus amigos.",
    trailerUrl: "trailers/miraculous-world1.mp4",
    image: "https://pauladeveraescritora.com/wp-content/uploads/2021/03/aea95-1w3ptjgqjakmpvru9bunw_a.jpeg",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/bc252fa9-cb15-4ae8-9ab5-d58011ca4786/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1TPUdqv1A3hmkIJYOMVJ-iyVohR4PRWkH/preview"
  },
  {
    id: "miraculous-world2",
    title: "Miraculous World Shangai: La Leyenda de LadyDragon",
    year: 2021,
    duration: "52min",
    rating: "TV-G",
    genres: ["Animación", "Aventura","Infantil"],
    description:"Marinette viaja a Shanghái para visitar a su tío Wang, pero le roban su bolso con Tikki y el Miraculous de Ladybug. Sola, conoce a Fei, una joven ingeniosa que inicialmente le roba el bolso, pero que se convierte en su aliada. Juntas, descubren una nueva joya mágica llamada Prodigio, que Hawk Moth también está buscando en la ciudad.",
    trailerUrl: "trailers/miraculous-world2.mp4",
    image: "images/miraculous-world-2.webp",
    post: "https://bandai.com.mx/blog/wp-content/uploads/2022/09/maxresdefault-1024x576.jpeg",
    movie: "https://drive.google.com/file/d/1yA_UuoOznsItmT7W0CkAFq8KTgBAQGt5/preview"
  },
  {
    id: "miraculous-world3",
    title: "Miraculous World París: Las Aventuras de Shadowbug y Claw Noir",
    year: 2022,
    duration: "52min",
    rating: "PTV-G",
    genres: ["Animación", "Aventura","Infantil","Acción","Fantasía"],
    description:"De manera repentina, milagrosos portadores de otro mundo aparecen en París. Estos misteriosos personajes proceden de un universo paralelo en el que todo está al revés. En ese lugar, Shadybug, Claw Noir y los demás son los villanos, mientras que el portador de la mariposa, Betterfly, es un héroe.",
    trailerUrl: "images/miraculous-paris.jpg",
    image: "https://br.web.img2.acsta.net/pictures/23/10/11/15/07/5725639.jpg",
    movie: "https://drive.google.com/file/d/1Eh6czDWVDupIAlkClf5Ec1OSZcBgbxj0/preview",
    post : "https://www.comingsoon.net/wp-content/uploads/sites/3/2024/02/004-1.jpg?resize=1200,630"
  },
  {
    id: "miraculous-world4",
    title: "Miraculous World Londres: Chronobug al filo del tiempo",
    year: 2024,
    duration: "52min",
    rating: "TV-G",
    genres: ["Animación", "Aventura","Infantil","Acción","Fantasía"],
    description:"Para salvar el futuro de un destino terrible, Marinette se convierte en Chronobug y se une a Bunnyx para derrotar a un villano fantasma(Spectral Looter) y a un misterioso oponente que viaja a través del tiempo(Timestalker).",
    trailerUrl: sampleTrailer,
    image: "https://preview.redd.it/a-synopsis-of-my-rewrite-of-the-london-special-v0-vjr5qh78pwmf1.jpeg?auto=webp&s=f707069bd41611b6949fbcbb60708f5c0330f27e",
    movie: "https://drive.google.com/file/d/1lj_1bQM62XxUqEG9_taRrZcnaGg9cldN/preview",
    post : "https://i.redd.it/miraculous-ladybug-london-special-what-side-are-you-on-v0-1zclp7pwp9pd1.jpg?width=1851&format=pjpg&auto=webp&s=e5d35522b0d9272fa6ec4bef6f58b4f1714a949a"
  },
  {
    id: "miraculous-world5",
    title: "Proximamente (2026): Miraculous World Tokio: Fuerza Estelar",
    year: 2025,
    duration: "52min",
    rating: "TV-G",
    genres: ["Animación", "Aventura","Infantil","Acción","Fantasía"],
    description:"Cuando Ladybug viaja a Tokio, conoce a Miki y Kazuno, viejos amigos de Kagami, miembros de la Stellar Force, un equipo japonés de superhéroes. Juntos, unen fuerzas para detener a un nuevo supervillano que busca sembrar el caos en la ciudad.",
    trailerUrl: sampleTrailer,
    image: "images/miraculous-world-5.webp",
    post : "posters/miraculous-tokio.jpg",
    movie: "aun no"
  },
  {
    id: "miraculous-awakening",
    title: "Miraculous Awakenig",
    year: 2023,
    duration: "1h 39min",
    rating: "PG-",
    genres: ["Animación", "Aventura", "Romance","Infantil","Músical"],
    description:"Un guardián de joyas mágicas convierte a una chica peculiar y a un chico popular en superhéroes. No obstante, jamás podrán revelar su verdadera identidad, ni siquiera el uno al otro.",
    trailerUrl: "trailers/miraculous-awakening.mp4",
    image: "https://preview.redd.it/predictions-hopes-for-the-miraculous-awakening-sequels-v0-i9xn116q7jtb1.jpg?width=640&crop=smart&auto=webp&s=282d8dd69dbe6cce784798e6029b62fb3ca7fbfa",
    post: "https://miraculous.to/global_data/img/S0E03_2025-08-18_17-38-16.webp",
    movie: "https://drive.google.com/file/d/1LxopTMByDv1hArzUF0mnjodfHOoHJx4h/preview"
  },
  {
    id: "sonic-the-hedgehog",
    title: "Sonic",
    year: 2020,
    duration: "1h 39min",
    rating: "PG-13",
    genres: ["Infantil","Comedia"],
    description:"Sonic intenta atravesar las complejidades de la vida en la Tierra con su nuevo mejor amigo, un humano llamado Tom Wachowski. Deberán unir sus fuerzas para evitar que el malvado Dr. Robotnik capture a Sonic y use sus poderes para dominar el mundo.",
    trailerUrl: "trailers/sonic-the-hedgehog.mp4",
    image: "https://upload.wikimedia.org/wikipedia/en/4/45/Sonic_the_Hedgehog_film_poster.jpg",
    post: "https://thumbnails.cbsig.net/CBS_Production_Entertainment_VMS/2021/04/22/1888618563964/STH_SAlone_16_9_1920x1080_2995303_1920x1080.jpg",
    movie: "https://drive.google.com/file/d/1aYLsDe1HnNSqVjS7v_tiT-ztdcG3z7eU/preview"
  },
  {
    id: "sonic-the-hedgehog-2",
    title: "Sonic 2",
    year: 2022,
    duration: "2h 2min",
    rating: "PG",
    genres: ["Infantil","Acción"],
    description:"Dr. Robotnik escapó del planeta hongo y busca aliarse con Knuckles para encontrar la Esmeralda Maestra, que tiene el poder de hacer realidad los pensamientos. Sonic, ahora intentando ser un héroe, se une con Tails para encontrar la gema antes que sus enemigos.",
    trailerUrl: sampleTrailer,
    image: "https://es.web.img3.acsta.net/pictures/22/02/18/10/20/5195258.jpg",
    post: "https://diariodevenusville.com/wp-content/uploads/2022/04/sonic_the_hedgehog_two_00.jpg",
    movie: "https://drive.google.com/file/d/1F6fK3gCNh5afr7ARKLWIRgvZ6iyUWnko/preview"
  },
  {
    id: "sonic-the-hedgehog-3",
    title: "Sonic 3: Próximamente",
    year: 2024,
    duration: "2h 2min",
    rating: "PG",
    genres: ["Infantil","Acción"],
    description:"Sonic, Tails y Knuckles se enfrentan a un nuevo y poderoso rival, Shadow, un erizo oscuro con poderes similares a los de Sonic. Shadow, que ha estado en estasis por 50 años, es despertado por el Dr. Gerald Robotnik, abulo del Dr. Eggman, quien desea usarlo para sus planes.",
    trailerUrl: sampleTrailer,
    image: "https://dx35vtwkllhj9.cloudfront.net/paramountpictures/sonic-the-hedgehog-3/images/regions/ar/onesheet.jpg",
    post: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiSTsxRDCZ5qygQdB8rPXOfIXWt3-5HIMVoQVEDdfbcqPm2SxYzlIXlR5GbfeJRTKeaPeDQTDRWg1fhUxensydQeNGWoZ7huNzPH5flmZBeQN1R4oBoddLJW_NN_cqsYGF1d2KntyJSjK6n42AJF0VbVoC3xMbsgsHlU7O_ZTXvfnr17hU2P-bgc0dNdhQN/s1196/69.jpg",
    movie: ""
  },
  {
    id: "five-nights-at-freddys",
    title: "Five Nights At Freddy's",
    year: 2023,
    duration: "1h 50min",
    rating: "PG-13",
    genres: ["Terror","Misterio"],
    description:"Mike Schmidt, un guardia de seguridad con problemas que empieza a trabajar en el turno de noche de la abandonada pizzería Freddy Fazbear's Pizza. A medida que pasa sus noches en el trabajo, descubre que las mascotas animatrónicas del lugar cobran vida de manera aterradora, lo que lleva a situaciones de suspense y terror. La trama explora el oscuro secreto de la pizzería, donde los animatrónicos están poseídos por las almas de niños secuestrados.",
    trailerUrl: "trailers/five-nights-at-freddys.mp4",
    image: "https://m.media-amazon.com/images/M/MV5BNzFkMDE2ZmEtOWMwNy00MWM2LThlNjMtZWQzNWY5MTJjZjcxXkEyXkFqcGc@._V1_.jpg",
    post: "https://www.nintenderos.com/wp-content/uploads/2023/09/fnaf-pelicula-1.jpg",
    movie: "https://drive.google.com/file/d/1NTEnMppzmWsNF0ufujXQp_6tr9i09JPF/preview"
  },
  {
    id: "five-nights-at-freddys2",
    title: "Five Nights At Freddy's 2: Próximamente",
    year: 2026,
    duration: "1h 45min",
    rating: "PG-13",
    genres: ["Terror","Misterio"],
    description:"Ha pasado un año desde la pesadilla sobrenatural en la pizzería Freddy Fazbear. La historia de lo que ocurrió allí se ha convertido en leyenda local, dando pie al primer “Fazfest”. Mike y Vanessa han mantenido en secreto la verdad a Abby, la hermana de 11 años de Mike. Pero cuando Abby decide reencontrarse con Freddy, Bonnie, Chica y Foxy, desata una serie de eventos aterradores que revelarán oscuros secretos sobre el origen de Freddy’s, desvelando un horror oculto por décadas.",
    trailerUrl: "trailers/five-nights-at-freddys2.mp4",
    image: "https://m.media-amazon.com/images/M/MV5BZmQ3NmIxNTgtYjFiNS00NzliLWI0YzAtZDkxY2E0YWIxZDEwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    post: "https://i.ytimg.com/vi/D0hX6VvGgBg/maxresdefault.jpg",
    movie: ""
  },
  {
    id: "five-nights-at-freddys3",
    title: "Five Nights At Freddy's 3: Próximamente",
    year: 2029,
    duration: "1h 50min",
    rating: "PG-13",
    genres: ["Terror","Misterio"],
    description:"Mike Schmidt se dirige a Fazbear's Fright: The Horror Attraction después de enterarse que el alma de William Afton esta dentro del animatrónico Spring-Bonnie, y este volvió para vengarse.",
    trailerUrl: sampleTrailer,
    image: "images/five-nights-at-freddys-3-movie-poster-fan-made-by-me-model-v0-jv59k3jszvmf1.webp",
    post: "https://nintenduo.com/wp-content/uploads/2024/09/FNAF-3-Pelicula-Destacada.webp",
    movie: ""
  },
  {
    id: "five-nights-at-freddys4",
    title: "Five Nights At Freddy's 4: Próximamente",
    year: 2035,
    duration: "1h 50min",
    rating: "PG-13",
    genres: ["Terror","Misterio"],
    description:"El niño Crying es atormentado por su hermano Mike junto con sus amigos cinco dás antes de su cumpleaños, y a causa de esto tiene pesadillas con animatrónicos que lo atormentan y tendrá que sobrevivir las cinco noches antes de su cumpleaños.",
    trailerUrl: sampleTrailer,
    image: "images/@fredbearfilms.jpg",
    post: "https://store-images.s-microsoft.com/image/apps.27998.14319236246610425.66fb0c70-79cc-471f-8a96-e56f4d317469.768e364a-76d9-473e-a1c8-c602e834dfdd?q=90&w=480&h=270",
    movie: ""
  },
  {
    id: "logan-wolverine",
    title: "Logan • Wolverine",
    year: 2017,
    duration: "2h 17min",
    rating: "PG-13",
    genres: ["Animación", "Ciencia Ficción", "Superhéroes"],
    description:"En un futuro cercano donde los mutantes están casi extintos, un cansado y envejecido Logan, cuyos poderes curativos están disminuyendo, se gana la vida como conductor de limusinas y cuida a un Profesor X enfermo y debilitado. Su vida cambia drásticamente cuando una mujer le pide que proteja a una joven mutante llamada Laura, quien es perseguida por fuerzas oscuras y posee poderes similares a los de él. Juntos, Logan, Charles y Laura emprenden un viaje para llevar a la niña a un refugio seguro llamado «Edén», enfrentándose a una peligrosa conspiración mientras Logan busca la redención.",
    trailerUrl: sampleTrailer,
    image: "https://preview.redd.it/is-wolverine-from-logan-2017-the-same-wolverine-as-the-one-v0-09qri59kyggd1.jpeg?auto=webp&s=27cb3bb8ea0987722b7837508d9007110b68ba6b",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/cf7b0eb8-e314-4ba0-8d89-398e02da4103/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/11LZONN67ENZ7vo7wPpIPg2c6K4RzqLqW/preview"
  },
  {
    id: "deadpool",
    title: "DeadPool: Próximamente",
    year: 2016,
    duration: "2h 08min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Deadpool cuenta la historia de Wade Wilson, un mercenario que, tras ser diagnosticado con cáncer terminal, se somete a un experimento para curarse que le otorga un factor de curación y lo desfigura. Con su nuevo aspecto y un sentido del humor retorcido, adopta la identidad de Deadpool para cazar al villano que arruinó su vida y, a pesar de sus temores, buscar a su novia.",
    trailerUrl: sampleTrailer,
    image: "images/deadpool.png",
    post: "posters/.jpg",
    movie: "aun no"
  },
  {
    id: "deadpool2",
    title: "DeadPool 2: Próximamente",
    year: 2018,
    duration: "2h 08min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Deadpool debe proteger a Russell, un adolescente mutante, de Cable, un soldado del futuro genéticamente modificado. Deadpool se alía con otros superhéroes para poder derrotar al poderoso Cable.",
    trailerUrl: sampleTrailer,
    image: "images/deadpool2.jpg",
    post: "",
    movie: "aun no"
  },
  {
    id: "deadpool3",
    title: "DeadPool 3 • Wolverine",
    year: 2024,
    duration: "2h 08min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Wade Wilson (Deadpool) abandona su retiro para unirse a una versión alterna de Wolverine, con el objetivo de salvar el multiverso de una amenaza externa. La historia comienza cuando la Autoridad de Variación Temporal (TVA) interrumpe la vida de Wade, llevándolo a una misión para enfrentar una crisis que podría borrar su universo de la existencia.",
    trailerUrl: sampleTrailer,
    image: "https://moviepostermexico.com/cdn/shop/files/deadpool_and_wolverine_ver6_xlg_1024x1024@2x.jpg?v=1725044429",
    post: "https://d2d7ho1ae66ldi.cloudfront.net/ArquivoNoticias/1facf04c-c215-11ee-aa78-d602bea5d5c0/deadpool-3-trailer.jpg",
    movie: "https://drive.google.com/file/d/1w9pPohiLbkp3GTjTJNqPsh60khrX68Ab/preview"
  },
  {
    id: "tinkerbel",
    title: "TinkerBell",
    year: 2008,
    duration: "1h 23min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Viaja al secreto mundo de Pixie Hollow y escucha cantar a Tinker Bell mientras se revela la historia de la famosa hada de Disney. ¿Te preguntaste cómo surge el brillo de la naturaleza? ¿Quién le da luz y color entre las estaciones? Tinker Bell y sus cuatro mejores amigas hadas convierten el invierno en primavera y aprenden la importancia de ser fiel a uno mismo.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/54ee3152e0e330b2a9d00c2a6ac6bf6a345aa38d4b19264ada06ef6029b8deed.jpg",
    movie: "https://drive.google.com/file/d/15hdvpjmUCJ9kNnUfOn5JOuVqLpQiVkR4/preview"
  },
  {
    id: "tinkerbel2",
    title: "TinkerBell 2: EL Tesoro Perdido",
    year: 2009,
    duration: "1h 25min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Saldrá una luna cosecha azul, y las hadas utilizarán una piedra lunar para restaurar el Árbol del Polvillo de Hadas, la fuente de su magia. Pero cuando Tinker Bell pone en riesgo todo Pixie Hollow, deberá aventurarse por el mar en una búsqueda para arreglar las cosas. Con su amigo Terence y la luciérnaga encantadora y pícara Blaze, Tink se enfrentará a un nuevo mundo y descubrirá el mejor tesoro.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/e6c0b227ea58c607a5812d7f908a0665c85154f7dd1527ce9694fdb386b43bb2.jpg",
    post: "",
    movie: "https://drive.google.com/file/d/1iL5GrlinMujHqedzyQU0ebS7gVaSCkPP/preview"
  },
  {
    id: "tinkerbel3",
    title: "TinkerBell 3: Hadas al Rescate",
    year: 2010,
    duration: "1h 16min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Antes de conocer a Wendy y los Niños Perdidos, Tinker Bell conoció a Lizzy, una niña que cree en las hadas. En la campiña se da un encuentro cuando Tink es descubierta por Lizzy. Sus mundos se unen y Tink desarrolla un lazo con la niña curiosa que necesita una amiga. Sus hadas compañeras lanzan un audaz rescate, y Tinker Bell pone en riesgo su seguridad y el futuro de las hadas.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/I/81cwwSrr5OL._AC_UF894,1000_QL80_.jpg",
    post: "",
    movie: "https://drive.google.com/file/d/1shBNCAb3QkavzXx7PKbe8HLahWQo7fCt/preview"
  },
  {
    id: "tinkerbel4",
    title: "TinkerBell 4: El Secreto de las Hadas",
    year: 2012,
    duration: "1h 15min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Una misteriosa fuerza atrae a Tink para cruzar la frontera hacia el desconocido mundo de los Bosques de Invierno, un lugar donde las hadas de Pixie Hollow tienen prohibido ir. Allí descubre un secreto que cambiará su vida para siempre: tiene una hermana llamada Periwinkle. Cuando Pixie Hollow se ve amenazado, el dúo debe trabajar unido para salvar ambos mundos.",
    trailerUrl: sampleTrailer,
    image: "https://es.web.img3.acsta.net/medias/nmedia/18/91/57/38/20153488.jpg",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/1ca81c90-6871-47be-b6f1-3057b17e48e5/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1FbnSkyTL26eRGxc-PZGHgQLz7Kqpa0GB/preview"
  },
  {
    id: "tinkerbel5",
    title: "TinkerBell 5: La Hada Pirata",
    year: 2014,
    duration: "1h 30min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Desde el mundo de Peter Pan, llega una aventura sobre Zarina, un hada inteligente y ambiciosa cautivada por el polvillo de hada azul y sus infinitas posibilidades. Cuando las ideas salvajes de Zarina la meten en problemas, huye de la tierra de las hadas y se une a los piratas intrigantes de Skull Rock. Tinker Bell y sus amigos deben encontrar a Zarina, y luchan contra la banda de piratas liderada por un grumete llamado James, quien pronto se hará conocido como el propio capitán Garfio.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/080efd725db32d326b330fc571906f45804046d1f387839a0d66b12a0e1ca22c.jpg",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/3fb1340f-6ae4-48c5-8b96-d249d828aec6/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1TYB_T6hH39nAcvvpARykmTiNOdw2rKAQ/preview"
  },
  {
    id: "tinkerbel6",
    title: "TinkerBell 6: La Leyenda de la Bestia de Nunca Jamás",
    year: 2014,
    duration: "1h 16min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"El antiguo mito de una criatura legendaria, la Bestia de Nunca Jamás, provoca curiosidad en Tinker Bell y su amiga Fawn, un hada de los animales que romperá las reglas para ayudar a cualquier animal que lo necesite. Pero esta criatura no es bienvenida en la Tierra de las Hadas, y las hadas exploradoras pretenden capturarla. Fawn, que ve un corazón tierno bajo su hosco exterior, deberá convencer a sus amigas de rescatar a la Bestia de Nunca Jamás. Algunas secuencias o patrones de luces intermitentes pueden afectar a espectadores fotosensibles.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/I/81FBqg51uoL._AC_UF894,1000_QL80_.jpg",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/0cc76721-570b-4ecc-bf3c-ed6e30103f93/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1gj_AJBWsrdK17wGRb0TX9q2ntOmY8F2l/preview"
  },
  {
    id: "finding-nemo",
    title: "Buscando a Nemo: Próximamente",
    year: 2003,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Una esposa(Coral) asesinada por un asesino serial y de su hijo(Nemo) que tiene un problema físico, tiempo después su hijo es secuestrado y el padre(Marlin) tiene que rastrear y perseguir al secuestrador por varios kilómetros con ayuda de una mujer(Dory) que tiene problemas mentales.",
    trailerUrl: sampleTrailer,
    image: "images/finding-nemo.jpeg",
    post: "",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "finding-dory-2016",
    title: "Buscando a Dory",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/f376d089a91798287747dc6c76644f7b76e9738ce177777db52c1f4167582b23.jpg",
    post: "https://www.eje21.com.co/site/wp-content/uploads/2013/04/buscando%20a%20dory.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "Deep-Sea-Mutant-Snake",
    title: "Anaconda El Despertar: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Una mujer trata de conseguir pruebas contra una empresa biológica que es culpable por la muerte de su prometido. En compañía de un amigo, la mujer se dirige a una isla en la que ocurren demasiadas muertes sospechosas.",
    trailerUrl: sampleTrailer,
    image: "images/Deep-Sea-Mutant-Snake.webp",
    post: "https://i.ytimg.com/vi/DN9hIg5Qx6s/maxresdefault.jpg",
    movie: "aun no"
  },
  {
    id: "oni-goroshi",
    title: "Oni Goroshi - La Ciudad de los Demonios: Próximamente",
    year: 2025,
    estreno: "Proximamente",
    duration: "1h 47min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Inculpado por el asesinato de su familia y dado por muerto, un asesino a sueldo retirado no se detendrá ante nada para vengarse de los demonios enmascarados que se han apoderado de su ciudad.",
    trailerUrl: sampleTrailer,
    image: "https://images.justwatch.com/poster/326314627/s718/demon-city.jpg",
    post: "https://a.storyblok.com/f/178900/960x506/416c7809b7/onigoroshi-live-action-header.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "a_minecraft-movie",
    title: "Una Pelicula de Minecraft: Próximamente",
    estreno: "Proximamente",
    year: 2025,
    duration: "1h 41min",
    rating: "PG-13",
    genres: ["Fantasía", "Aventura"],
    description:"Cuatro inadaptados son arrastrados por un portal al Overworld, un misterioso lugar que se nutre de la imaginación. Para volver a casa, tendrán que dominar el terreno mientras se embarcan en una búsqueda con un artesano llamado...Steeeeeeeeve.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/76646f9affd837b3a4cae5e4ceca49c647c2ac1e2974112eb11d51741676e14d.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/cbfd90bac7ae3dafec83553a6325d57b3cf4308f694b07237bb9bf5c9e9205ab._SX1080_FMjpg_.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "truman-show",
    title: "El Show de Truman: Historia de una vida",
    year: 1998,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Ciencia Ficción","Comedia"],
    description:"Truman Burbank, un feliz agente de seguros, cree llevar una vida normal, pero no sabe que está siendo grabado las 24 horas del día y que todo lo que hace se emite en televisión.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/73eb129e028d5f3946c1ef65be5238088b6ed35064926b6a120d96ac81930ae0.jpg",
    post: "https://educarpersonas.com/wp-content/uploads/2023/05/truman.jpg",
    movie: "https://drive.google.com/file/d/1Sao8mHfFPMDhyV03w7X8dmh-NVEWj5Nb/preview"
  },
  {
    id: "apocalypto",
    title: "Apocalipto",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/37a1cbe1b9066e7535fd7874fcfc4778e9f746d7a5365680a27761a6cac1da4e.jpg",
    post: "",
    movie: "https://drive.google.com/file/d/1pwo5WpW_nZQnQzlXa3B6xJYEYZW__qbg/preview"
  },
  {
    id: "bright-burn",
    title: "El Hijo de la Oscuridad: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/bright-burn.webp",
    post: "https://m.media-amazon.com/images/S/pv-target-images/65c7ac8246393ba005c09e0b8d5120f200499436242e2496f6c90789236d91c3.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "shrek",
    title: "Shrek",
    year: 2001,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Un ogro llamado Shrek vive en su pantano, pero su preciada soledad se ve súbitamente interrumpida por la invasión de los ruidosos personajes de los cuentos de hadas. Todos fueron expulsados de sus reinos por el malvado Lord Farquaad. Decidido a salvar su hogar, Shrek hace un trato con Farquaad y se prepara para rescatar a la princesa Fiona, quien será la esposa de Farquaad.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/030f9ae65cadc9afc0e3c51ed35d2ddeb814f213d7a87fc5aa4445738ebb32b9.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/5a5cf867eb9d4fc1e5d44fa81bca4ced972e299967c7d040f5ff49fef7b49b51.jpg",
    movie: "https://drive.google.com/file/d/1F__HmYqKuxrvZHAFu2bwZxi1AyI2mk1p/view?usp=sharing"
  },
  {
    id: "shrek-2",
    title: "Shrek 2",
    year: 2004,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Los padres de la princesa y reyes de Muy, Muy Lejano invitan a cenar Shrek y Fiona, pero el rey Harold descubre que su yerno es un ogro y acude al Hada Madrina para alejar a Shrek de Fiona y lograr que se case con el guapo Príncipe Encantador.",
    trailerUrl: sampleTrailer,
    image: "https://playmax.xyz/img/c/400/1/1439814412/487.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/f8b6c8fa6508e343804cd3bbe314ae604d234a2fec1bf9a3cdd91b872feb93dc.jpg",
    movie: "/preview"
  },
  {
    id: "shrek-3",
    title: "Shrek 3",
    year: 2007,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Shrek y sus amigos van en busca del verdadero heredero de la Tierra Muy Muy Lejana, mientras la Princesa Fiona intenta evitar que el Príncipe Encantador ocupe el trono.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/5b38695d4ad8fd3f6d59c9dec6e58dcce5113dbe58ba079a5c6034104fad7a84.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/837b0e7c4907d6dc41949aba42156710ecbb936bac5e82ee47f3deef6ceb049f.jpg",
    movie: "/preview"
  },
  {
    id: "shrek-4",
    title: "Shrek 4",
    year: 2010,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Instalado en su vida matrimonial y totalmente domesticado, Shrek empieza a extrañar los días en los que él se sentía como un verdadero ogro. Engañado para firmar un contrato con el tortuoso Rumpelstiltskin, él se encuentra a sí mismo en una versión alterna de Muy Muy Lejano, donde los ogros son cazados, Rumpelstiltskin manda, y él y Fiona nunca se conocieron. Shrek debe hallar la forma de cancelar el contrato para restaurar su mundo y reclamar su amor verdadero.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/a330d6bf726c4af2b90f2df1c3ebd0d0a61b2344ac70441bb9e9206c2b2674da.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/8c42560ed597df398e1d76ba5bbd1e4de50226d38f63d8e3b3a65b68b564168c.jpg",
    movie: "/preview"
  },
  {
    id: "The_Gangster_The_Cop_The_Devil",
    title: "El Gangster, El Policía y El Diablo: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/The_Gangster_The_Cop_The_Devil.jpg",
    post: "",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "final destination_6-bloodlines",
    title: "Destino Final - Lazos de Sangre: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/destino-final-lazos-de-sangre.jpg",
    post: "",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "captain-america",
    title: "Capitan America - El Primer Vengador",
    year: 2011,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Tras tres meses de someterse a un programa de entrenamiento físico y táctico, encomiendan a Steve Rogers su primera misión como Capitán América. Armado con un escudo indestructible, emprende la guerra contra la perversa organización HYDRA.",
    trailerUrl: sampleTrailer,
    image: "images/captain-america.webp",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/806ead63-e2ad-403e-8514-5b1ea63bb2d7/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1yJGYgjq2mlMKQQXwFf2QAamhGZwZukPm/preview"
  },
  {
    id: "captain-america2",
    title: "Capitan America 2 - El Soldado del Invierno: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"",
    trailerUrl: sampleTrailer,
    image: "images/captain-america2.jpg",
    post: "",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "captain-america3",
    title: "Capitan America 3 - Civil War",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    post: "https://todoinfantil.com/img/not_img/civil-war-capitan-america-marvel.png",
    image: "images/captain-america3.webp",
    movie: "https://drive.google.com/file/d/15rJMLextuATJNTDphVzNpwHTre1XCMAr/preview"
  },
  {
    id: "toy-story",
    title: "Toy Story: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBzlHxBqvhvJFyM6qx1PSuKzjDmahiwmLd7w&s",
    post: "https://m.media-amazon.com/images/S/pv-target-images/8d3f810be9313db33593677e5baac43e1e96d527cbf8b0f4edbf2721b5c5846f._UR1920,1080_SX500_FMjpg_.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "toy-story-2",
    title: "Toy Story 2: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/b14b33a4a541520ab9d9d217678375991e5adc5e400dfcd7ff4bde8966669863.jpg",
    post: "",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "toy-story-3",
    title: "Toy Story 3: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/a460a32bc1a4a2cbd111a1fd95d11291b6fa6542aae39cc67c1f8def4d6a6d58.jpg",
    post: "",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "toy-story-4",
    title: "Toy Story 4",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Bonnie crea un nuevo juguete llamado Forky, un tenedor que piensa que es basura, Woody se embarca en una aventura para protegerlo y mostrarle su propósito como juguete. En el camino, se reencuentra con Bo Peep y descubre que el mundo es más grande de lo que imaginaba para un juguete, mientras que Forky lucha con su nueva identidad.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/858666a691e20057054f181e55871fc9f7ebbe9004a181b89e6df322e73c1112.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/51b83557582e866e9dd96da2654f9433ac16886a7de563c02604c328357f9503.jpg",
    movie: "https://drive.google.com/file/d/1MTNURDdhI15j-JnM5o9QqiE5ZOzyXbOq/preview"
  },
  {
    id: "toy-story-5",
    title: "Toy Story 5: Próximamente",
    year: 2026,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://lumiere-a.akamaihd.net/v1/images/toy_story_c00b8d79.jpeg?region=0,0,1080,1350",
    post: "",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "guardians-of-the-galaxy",
    title: "Guardianes de la Galaxia: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/M/MV5BYWI0NTNlN2MtMWRjNy00M2QwLWFlZTgtZTlkMTZiYTU2NTk1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    post: "",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "guardians-of-the-galaxy-2",
    title: "Guardianes de la Galaxia 2",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Los Guardianes son contratados para proteger unas baterías para los Soberanos, pero Rocket las roba, provocando una persecución. Los Guardianes son rescatados por Ego, el padre de Peter Quill, quien los invita a su planeta. Allí, descubren que Ego es un ser celestial.",
    trailerUrl: "",
    image: "images/guardianes-de-la-galaxia-2.avif",
    post: "https://m.media-amazon.com/images/S/pv-target-images/b9c4b17bdf6db1ded2fc0035b46202100df7dc741dc98ddaf8f9ea817e8e74d1.jpg",
    movie: "https://drive.google.com/file/d/10m6vG2w5eXZ_yPxwEJ1CFJFIORMvd6ME/preview"
  },
  {
    id: "guardians-of-the-galaxy-3",
    title: "Guardianes de la Galaxia 3: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://lumiere-a.akamaihd.net/v1/images/lat_2ae5e247.jpeg",
    post: "",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "spies-in-disguise",
    title: "Espias a Escondidas",
    year: 2019,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"El espía Lance Sterling y el científico Walter Beckett son polos opuestos: el agente es afable y caballeroso, mientras que el inventor no sabe comportarse en público. Sin embargo, si no aprenden a trabajar en equipo, el mundo está perdido.",
    trailerUrl: sampleTrailer,
    image: "images/spies-in-disguise.webp",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/fe2b447f-3e0f-4cf2-82d4-633caf5f7450/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/10g6bvHCasxrzhiywS3lXDmxd8n4X2Kx7/preview"
  },
  {
    id: "sleepy-hollow",
    title: "La Leyenda del Jinete Sin Cabeza",
    year: 1999,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Un policía de la época colonial descubre una serie de horribles decapitaciones en una villa del norte de Nueva York.",
    trailerUrl: sampleTrailer,
    image: "images/la-leyenda-del-jinete-sin-cabeza.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/c5a31e848714a2464837ca1cf04096c8bb6b1a6f351611d44b58cf1d0848e65e.jpg",
    movie: "https://drive.google.com/file/d/1dxrITG2BKcAyWTq5i5Etah1Fp6iwWYoC/preview"
  },
  {
    id: "the-last-airbender",
    title: "El Ultimo Maestro del Aire: Próximamente",
    year: 2010,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/471e228a610a18f78a0b00d2c96321a6fb42397f035d1de4da2637e1330dc05e.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/5a16998dd7d5f858e0a9e4e47a8be93ccd53a00ffa978bd124338a476f612fb8._SX1080_FMjpg_.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "kung-fu-panda",
    title: "Kung fu Panda: Próximamente",
    year: 2008,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTND_aT98Q9K37HgTKJwBqZZVCPQGrMTMV44w&s",
    post:"https://i.ytimg.com/vi/pINQLcVgwvU/sddefault.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "kung-fu-panda-2",
    title: "Kunfu Panda 2: Próximamente",
    year: 2011,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://es.web.img3.acsta.net/medias/nmedia/18/82/36/56/19734959.jpg",
    post: "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/0d054460-73d1-4c10-99d9-57b9438e1dfb/27b60aec-abf7-4812-9eec-4e28e7d5f652?host=wbd-images.prod-vod.h264.io&partner=beamcom",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "kung-fu-panda-3",
    title: "Kung fu Panda 3: Próximamente",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://zoomf7.net/wp-content/uploads/2016/03/24qz9huzy8k3cdo4hrwkmztt7gh.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "kung-fu-panda-4",
    title: "Kung fu Panda 4: Próximamente",
    year: 2024,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/1b2855d75a12c03f471c8fa132bb2bae77aeaadd4e8fbf76fd879378424133f8.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/20bafb36b2d7cf540655f0b79b6d175b71959ab86ac7a3e8cbf48b95c7036cb6.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "robocop-2014",
    title: "Robocop",
    year: 2011,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Una compañía utiliza los restos destrozados de un policía muerto para crear a un policía robot indestructible. El policía conserva su memoria y decide vengarse de sus asesinos.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/M/MV5BNDRkODU3MTktNTdjMi00OTkxLTljZjgtMzdhMGQxYTM4NjcwXkEyXkFqcGc@._V1_.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/8be920faafe8b3cb711f34697e4f9eadfac67b77c35d4e3bb259993432d2c395.jpg",
    movie: "https://drive.google.com/file/d/1Yup4h__yTj6cBzcHoKD_Jci4q68hbI8a/preview"
  }
];

// (Opcional) Exponerlo globalmente
window.MOVIES = MOVIES; 