// movies.js — versión corregida compatible con index.html

const sampleTrailer = "https://www.w3schools.com/html/mov_bbb.mp4"; // Tráiler genérico temporal

const MOVIES = [
  {
    id: "spiderman-into-the-spiderverse",
    title: "Spiderman: Un Nuevo Universo",
    year: 2018,
    duration: "1h 56min",
    rating: "PG",
    genres: ["Animación", "Aventura"],
    description: "Miles Morales se convierte en Spider-Man y conoce a otros héroes arácnidos de universos paralelos.",
    trailerUrl: "trailers/into-the-spiderverse.mp4",
    image: "https://images.justwatch.com/poster/100305541/s718/spider-man-un-nuevo-universo.jpg",
    post : "https://m.media-amazon.com/images/S/pv-target-images/6d7e5bcdbf18511aa8931caea5215bb9a5a73cc13fb4b5c45494c0d1828f0699.jpg",
    movie: "https://drive.google.com/file/d/1Gp-v1xvRausPDh9c88yxOSFusXM9dkwE/preview"
  },
  {
    id: "across-the-spiderverse",
    title: "Spider-Man 2: A través del Spiderverso",
    year: 2023,
    duration: "2h 20min 05s",
    rating: "PG",
    genres: ["Animación", "Acción", "Aventura", "Superhéroes"],
    description: "Después de reunirse con Gwen Stacy, el amigable vecino de tiempo completo de Brooklyn Spiderman, es lanzado a través del multiverso, donde se encuentra a un equipo de gente araña encomendada con proteger su mera existencia.",
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSdauvCqT1b2k3Yd53nraCJAXopp7g001RpnDdzPLY-jlFeLy9J",
    post: "https://m.media-amazon.com/images/S/pv-target-images/3c7c45988ed34fe4628aed9d51507061434432482279e1b69f8fd11ced6869bf._SX1080_FMjpg_.jpg",
    trailerUrl: "trailers/across-the-spiderverse(2).mp4",
    movie: "https://drive.google.com/file/d/11SMv4hmFUM71MWcPYm5qXf5j-tJgeAWp/preview"
  },
  {
    id: "beyond-into-the-spiderverse",
    title: "Spider-Man 3 Proximamente[2027]: Beyond into the spiderverse",
    year: 2027,
    duration: "2h 20min 05s",
    rating: "PG",
    genres: ["Animación", "Acción", "Aventura", "Superhéroes"],
    description: "Luego de ser mordido por una araña radioactiva, Miles Morales desarrolla misteriosos poderes que lo transforman en el Hombre Araña. Ahora deberá usar sus nuevas habilidades ante el malvado Kingpin, un enorme demente que puede abrir portales hacia otros universos.",
    image: "images/beyond-the-spiderverse.jpg",
    post: "https://m.media-amazon.com/images/M/MV5BMjQwZWExNzAtOTEzZC00NTI3LTk1MDctYjQ1M2M1MzQ5YzljXkEyXkFqcGc@._V1_.jpg",
    trailerUrl: "IJ3o8oX1nyjbsyfpDwkH-cS/preview",
    movie: "https://drive.google.com/file/d/11SMv4hmFUM71MWcPYm5qXf5j-tJgeAWp/preview"
  },
  {
    id: "face-off",
    title: "Contracara",
    year: 1997,
    duration: "2h 18min 57s",
    rating: "R",
    genres: ["Acción", "Thriller", "Crimen"],
    description:  "Un agente del FBI se somete a una cirugía experimental para asumir la identidad del terrorista que mató a su hijo. Pero las cosas salen terriblemente mal.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/c2668312b9f29fb8e5780ddcb9a183831f4acc01347c3b704e098f48477df639.jpg",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/0cbfc5e5-71fe-4605-99fc-1ae7f66d2dc0/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1FsEqOKWlq4zMSeYOF-7tp_UB4jTKujqn/preview"
  },
  {
    id: "interestellar",
    title: "Interestelar",
    year: 2014,
    duration: "2h 49min",
    rating: "PG-13",
    genres: ["Ciencia ficción", "Drama", "Aventura"],
    description:  "Un grupo de astronautas viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad mientras la Tierra agoniza.",
    trailerUrl: "trailers/interestellar.mp4",
    image: "https://pics.filmaffinity.com/Interstellar-366875261-large.jpg",
    post: "https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/aa5b9295-8f9c-44f5-809b-3f2b84badfbf/8a7dd34b09c9c25336a3d850d4c431455e1aaaf0.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom",
    movie: "https://drive.google.com/file/d/1cVVPgzsRjlombZxDsP2YWa9F9cHs0xa7/preview"
  },
  {
    id: "karatekid1984",
    title: "Karate Kid (1984)",
    year: 1984,
    duration: "2h 6min",
    rating: "PG",
    genres: ["Drama", "Deportes", "Inspiradora"],
    description:
      "Daniel se muda a California y sufre acoso hasta que un sabio maestro de karate, el Sr. Miyagi, le enseña el arte del equilibrio y la disciplina.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/S/pv-target-images/8525873a8c8da460d36c6230856d1080c6a995670b1e15100fd796d18d56bc3e.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/36c87917428a50fdbb5d7481433ddbddf544083e8d6d2b141ec61e84f5a5448c.jpg",
    movie: "https://drive.google.com/file/d/1vytWPJ8SuHa5cLsXWXQFHsCA26jYspc5/preview"
  },
  {
    id: "karate-kid-legends",
    title: "Karate Kid Leyendas",
    year: 2025,
    duration: "1h 34min",
    rating: "PG",
    genres: ["Infantil","Acción"],
    description:"Tras mudarse a Nueva York, el prodigio del kung fu Li Fong atrae una atención no deseada y se embarca en un viaje para participar en la competición de karate definitiva. Li fusiona sus estilos únicos para prepararse para un épico enfrentamiento.",
    trailerUrl: "trailers/karate-kid-legends.mp4",
    image: "https://m.media-amazon.com/images/S/pv-target-images/d57b76d7175a17c471fbabccf92ccd3fed7d53bfd4b35a41a76c9b64d81d5a33.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/44a88afaadb493bb565c0d418474ff016be1cdaf443448a37c44e345af79e265._UR1920,1080_.png",
    movie: "https://drive.google.com/file/d/1A26SVMjdf0MWh_HmFkXG_qtOv_C4lYK2/preview"
  },
  {
    id: "laleyendadeloschaneques",
    title: "La Leyenda de los Chaneques",
    year: 2023,
    duration: "1h 25min",
    rating: "A",
    genres: ["Animación", "Fantasía", "Aventura"],
    description: "Leo San Juan y sus amigos viajan a Veracruz, donde descubren que unos traviesos chaneques están causando estragos en la región.",
    trailerUrl: "trailers/la-leyenda-de-los-chaneques.mp4",
    image: "https://m.media-amazon.com/images/S/pv-target-images/1640bf4852cbd0ae978d1277489dc5849a7c1455ba9f5edcfaa60f631ae58bef.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/234088d196d0e848255707bf370ce9bfec12e57d2c77d1e5bc9dcacf001b5108.jpg",
    movie: "https://drive.google.com/file/d/1j2-DvVDho1-u6DoJhZpr3fG6mpyAMGL5/preview"
  },
  {
    id: "venom3",
    title: "Venom 3: The Last Dance",
    year: 2024,
    duration: "2h 0min",
    rating: "PG-13",
    genres: ["Acción", "Ciencia ficción"],
    description: "Eddie y Venom están huyendo. Perseguidos por sus dos mundos y con la red cerrándose, el dúo se ve obligado a tomar una decisión devastadora que echará el telón al último baile de Venom y Eddie.",
    trailerUrl: "trailers/venom-3.mp4",
    image: "https://m.media-amazon.com/images/S/pv-target-images/c2d6430ada2a73209fc05ff1e79cd3dfdf46c92326bed76262d40bd5033e2bb4.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/b6ecdea0a5f796ac6716aac314cd15b49bfd5efcb863aecaac91ef12a0fe3625.jpg",
    movie: "https://drive.google.com/file/d/1-I98WaJ_C622i2YMeBFjcEn43808KgmR/preview"
  },
  {
    id: "clockstoppers",
    title: "Tiempo Congelado",
    year: 2024,
    duration: "1h 55min",
    rating: "PG-13",
    genres: ["Suspenso", "Drama", "Ciencia ficción"],
    description: "Un adolescente y su amigo deben salvar a su padre de un hombre que ha pedido la construcción de dispositivo de tiempo.",
    trailerUrl: sampleTrailer,
    image: "https://m.media-amazon.com/images/M/MV5BYzhmZTExNjktYWNmYS00YzdmLTllZjktYTU5M2ViMDk1MTU4XkEyXkFqcGc@._V1_.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/498665c87a32081ff493eb39995ff60e6c42705eb9c3fc54fbca741099a7f2bd.jpg",
    movie: "https://drive.google.com/file/d/1mi8Ltlqx01KVDLKIIQXL0l05A_i5endV/preview"
  },
  {
    id: "lightyear",
    title: "Lightyear",
    year: 2022,
    duration: "1h 45min",
    rating: "PG",
    genres: ["Animación", "Aventura"],
    description: "Buzz y Alisha exploran el planeta T'Kani Prime y viven aventuras en el espacio-tiempo.",
    trailerUrl: "trailers/lightyear.mp4",
    image: "https://m.media-amazon.com/images/I/71EgLo5pqnL._AC_UF894,1000_QL80_.jpg",
    post: "https://cdn.bolivia.com/sdi/2022/07/21/lightyear-fecha-estreno-chris-evans-disney-plus-1050224.jpg",
    movie: "https://drive.google.com/file/d/1m5gLKdgBV2loj5qCDIgLakOnUS7SN5T4/preview"
  },
  {
    id: "mufasa",
    title: "Mufasa - El Rey León",
    year: 2024,
    duration: "1h 58min",
    rating: "PG-13",
    genres: ["Aventura","Musical"],
    description:"Una inundación separa al cachorro Mufasa de sus padres, pero el rey de los leones lo acoge como a uno de los suyos tras demostrar su valentía. Al crecer, una manada de leones desterrados y los celos de su hermana adoptiva lo pondrán en peligro.",
    trailerUrl: "trailers/mufasa.mp4",
    image: "https://images.justwatch.com/poster/326095284/s718/mufasa-el-rey-leon.jpg",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/018ffc14-acb8-44c6-82c7-3c4dd3091c3f/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1kpAxZOwLmSTcZZnHZ_vDlfNHqv9ZtGgz/preview"
  },
  {
    id: "how-train-your-dragon",
    title: "Cómo Entrenar a tu Dragón",
    year: 2014,
    duration: "1h 42min",
    rating: "PG",
    genres: ["Animación","Aventura","Infantil","Acción"],
    description:"Hipo y Chimuelo se enfrentan a cazadores de dragones para evitar la guerra.",
    trailerUrl: "trailers/dragon.mp4",
    image: "images/dragon.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/2216969f4080744c6652d39f24f3889577623e22dbb36656145b4c2d4939a107.jpg",
    movie: ""
  },
  {
    id: "how-train-your-dragon-2",
    title: "Cómo Entrenar a tu Dragón 2",
    year: 2014,
    duration: "1h 42min",
    rating: "PG",
    genres: ["Animación","Aventura","Infantil","Acción"],
    description:"Hipo y Chimuelo se enfrentan a cazadores de dragones para evitar la guerra.",
    trailerUrl: "trailers/dragon.mp4",
    image: "https://m.media-amazon.com/images/S/pv-target-images/23015dc809dd71e28155b18cc36279bb1874028facfc0419c23a1505e198970b.jpg",
    post: "https://m.media-amazon.com/images/S/pv-target-images/d58b307c15c88f7018175db9c3f91476d73f2bd82956cc099be1ee1a4099ca41.jpg",
    movie: "https://drive.google.com/file/d/1HoxHuCgIgetLZk6nuFE6nN9a_1YK9Py_/preview"
  },
  {
    id: "how-train-your-dragon-3",
    title: "Cómo Entrenar a tu Dragón 3 - El Mundo Oculto",
    year: 2019,
    duration: "1h 44min",
    rating: "PG",
    genres: ["Animación","Aventura","Infantil","Acción"],
    description:
      "Hipo y Chimuelo descubren un mundo oculto mientras luchan por proteger a su gente y a los dragones.",
    trailerUrl: "trailers/dragon3.mp4",
    image: "https://play-lh.googleusercontent.com/P6oso1hC1JGLsr1NT_V-74KR6KpJg7oX5Zmdso7-SJfrQHhgSxMk_gm87cV20MvQbBzn=w240-h480-rwg",
    post: "trailers/dragon3.mp4",
    movie: "https://drive.google.com/file/d/1x4CYvRvkriWKcL2aE0nqOJY1tPAq71I2/preview"
  },
  { id: "avatar-2009",
    title: "Avatar",
    year: 2009,
    duration: "2h 42min",
    rating: "PG-13",
    genres: ["Ciencia ficción", "Aventura"],
    description: "En un exuberante planeta llamado Pandora viven los Na'vi, seres que aparentan ser primitivos pero que en realidad son muy evolucionados. Debido a que el ambiente de Pandora es venenoso, los híbridos humanos/Na'vi, llamados Avatares, están relacionados con las mentes humanas, lo que les permite moverse libremente por Pandora. Jake Sully, un exinfante de marina paralítico se transforma a través de un Avatar, y se enamora de una mujer Na'vi..",
    trailerUrl: sampleTrailer,
    image: "images/avatar.jpeg",
    post: "https://spoilertown.com/wp-content/uploads/2024/07/avatar-2009.webp",
    movie: "https://drive.google.com/file/d/16JSSJ3zfvpZGG7zNGXqZ2DicCFyqrfGU/preview"
  },
  {
    id: "avatar2-elcaminodelagua",
    title: "Avatar 2 - El Camino del Agua",
    year: 2022,
    duration: "3h 12min",
    rating: "PG-13",
    genres: ["Ciencia ficción", "Aventura"],
    description: "Jake Sully y Neytiri deben proteger a su familia de nuevas amenazas en Pandora mientras exploran las profundidades oceánicas del planeta.",
    trailerUrl: sampleTrailer,
    image: "images/avatar2.jpeg",
    post: "posters/.jpg",
    movie: "https://drive.google.com/file/d/12RRSn0kLKUea3RbJlg32Z7zLZE7v__B5/preview"
  },
  {
    id: "avatar3-fireandash",
    title: "Avatar 3 Próximamente (2026) - Fuego y Cenizas",
    year: 2026,
    duration: "3h 12min",
    rating: "PG-13",
    genres: ["Ciencia ficción", "Aventura"],
    description:"Jake Sully y Neytiri deben proteger a su familia de nuevas amenazas en Pandora mientras exploran las profundidades oceánicas del planeta.",
    trailerUrl: "trailers/avatar3-fireandash.mp4",
    image: "https://media.glamour.mx/photos/6880137b2a74ff906caa7729/master/w_1600%2Cc_limit/avatar-fuego-y-cenizas-poster.jpg",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/41ae7704-8740-4eb8-bb01-e4285e3b9011/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/12RRSn0kLKUea3RbJlg32Z7zLZE7v__B5/preview"
  },
  {
    id: "flow",
    title: "Flow",
    year: 2024,
    duration: "1h 25min",
    rating: "PG",
    genres: ["Animación", "Drama"],
    description:
      "Un gato debe aprender a convivir con otros animales en un barco que flota sobre un mundo inundado.",
    trailerUrl: sampleTrailer,
    image: "https://apeiros173.github.io/ShareFilms-Peliculas-Gratis/flow.jpeg",
    post: "posters",
    movie: "https://drive.google.com/file/d/1VVd1JCyxkHXGpsYr-3-SaD68pijn1XFS/preview"
  },
  {
    id: "get-out",
    title: "Huye",
    year: 2017,
    duration: "1h 44min",
    rating: "R",
    genres: ["Terror", "Suspenso"],
    description: "Chris visita a los padres de su novia, pero descubre un siniestro secreto detrás de su aparente amabilidad.",
    trailerUrl: sampleTrailer,
    image: "https://apeiros173.github.io/ShareFilms-Peliculas-Gratis/images/get-out.jpeg",
    post: "",
    movie: "https://drive.google.com/file/d/1en6HYU4w0GfvSf3PT8ZAqcxzbHvCcjHB/preview"
  },
  {
    id: "rango",
    title: "Rango",
    year: 2011,
    duration: "1h 47min",
    rating: "PG",
    genres: ["Animación", "Aventura", "Comedia"],
    description: "Un camaleón doméstico se convierte en el héroe de un pueblo del Viejo Oeste.",
    trailerUrl: sampleTrailer,
    image: "https://apeiros173.github.io/ShareFilms-Peliculas-Gratis/images/rango.jpeg",
    post: "",
    movie: "https://drive.google.com/file/d/1SB357lg3QIGL5RvdfrJQ53_1jmnHNv7u/preview"
  },
  {
    id: "kpop-hunters",
    title: "Las Guerreras K-Pop",
    year: 2025,
    duration: "1h 36min",
    rating: "PG-13",
    genres: ["Acción", "Músical"],
    description: "Cuando no están llenando estadios, las superestrellas del k-pop Rumi, Mira y Zoey usan sus superpoderes secretos para proteger a sus fans de Gwi-Ma y los demonios.",
    trailerUrl: sampleTrailer,
    image: "https://apeiros173.github.io/ShareFilms-Peliculas-Gratis/huntrix.jpeg",
    post: "posters/.jpg",
    movie: "https://drive.google.com/file/u/0/d/1yn5s7n8Cf3hnMtJdND3xG6gMq0DO3kfO/preview"
  },
  {
    id: "fast-and-furious5",
    title: "Rápidos y Furiosos 5",
    year: 2011,
    duration: "2h 10min",
    rating: "PG-13",
    genres: ["Acción", "Crimen"],
    description: "Dom y Brian planean un último gran golpe en Río de Janeiro mientras son perseguidos por un agente federal.",
    trailerUrl: sampleTrailer,
    image: "images/fast-and-furius5.jpg",
    post: "",
    movie: "https://drive.google.com/file/d/1kkdCZcm_ynd7URwOML6jWAabSMSvArha/preview"
  },
  {
    id: "miraculous-world1",
    title: "Miraculous World Nueva York: Héroes Unidos",
    year: 2020,
    duration: "1h 03min",
    rating: "TV-G",
    genres: ["Animación", "Aventura","Infantil"],
    description:"Con motivo de la semana de la amistad franco-estadounidense, Marinette y su clase viajan a Nueva York: la ciudad de los superhéroes. Es la oportunidad para que Marinette pase tiempo con sus amigos.",
    trailerUrl: "trailers/miraculous-world1.mp4",
    image: "https://static.wikia.nocookie.net/miraculousladybug/images/8/81/Miraculous_World-_New_York.jpg/revision/latest/scale-to-width/360?cb=20201227040733&path-prefix=es",
    post: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/bc252fa9-cb15-4ae8-9ab5-d58011ca4786/compose?aspectRatio=1.78&format=webp&width=1200",
    movie: "https://drive.google.com/file/d/1TPUdqv1A3hmkIJYOMVJ-iyVohR4PRWkH/preview"
  },
  {
    id: "miraculous-world2",
    title: "Miraculous World Shangai: La Leyenda de LadyDragon",
    year: 2020,
    duration: "52min",
    rating: "TV-G",
    genres: ["Animación", "Aventura","Infantil"],
    description:"Con motivo de la semana de la amistad franco-estadounidense, Marinette y su clase viajan a Nueva York: la ciudad de los superhéroes. Es la oportunidad para que Marinette pase tiempo con sus amigos.",
    trailerUrl: "trailers/miraculous-world2.mp4",
    image: "https://static.wikia.nocookie.net/lady-bug/images/b/bd/Miraculous_Shanghai_Promotional_Poster_by_Olchus.png/revision/latest?cb=20210316210128",
    post: "https://bandai.com.mx/blog/wp-content/uploads/2022/09/maxresdefault-1024x576.jpeg",
    movie: "https://drive.google.com/file/d/1yA_UuoOznsItmT7W0CkAFq8KTgBAQGt5/preview"
  },
  {
    id: "miraculous-world3",
    title: "Miraculous World París: Las Aventuras de Shadowbug y Claw Noir",
    year: 2023,
    duration: "52min",
    rating: "PTV-G",
    genres: ["Animación", "Aventura","Infantil","Acción","Fantasía"],
    description:"Con motivo de la semana de la amistad franco-estadounidense, Marinette y su clase viajan a Nueva York: la ciudad de los superhéroes. Es la oportunidad para que Marinette pase tiempo con sus amigos.",
    trailerUrl: "images/miraculous-paris.jpg",
    image: "https://br.web.img2.acsta.net/pictures/23/10/11/15/07/5725639.jpg",
    movie: "https://drive.google.com/file/d/1Eh6czDWVDupIAlkClf5Ec1OSZcBgbxj0/preview",
    post : "https://www.comingsoon.net/wp-content/uploads/sites/3/2024/02/004-1.jpg?resize=1200,630"
  },
  {
    id: "miraculous-world4",
    title: "Miraculous World Londres: Chronobug al filo del tiempo",
    year: 2024,
    duration: "52min",
    rating: "TV-G",
    genres: ["Animación", "Aventura","Infantil","Acción","Fantasía"],
    description:"Marinette, ahora Chronobug, se une a Bunnyx para enfrentarse a un oponente misterioso que viaja en el tiempo...¡y que conoce la identidad secreta de Ladybug!",
    trailerUrl: sampleTrailer,
    image: "https://preview.redd.it/a-synopsis-of-my-rewrite-of-the-london-special-v0-vjr5qh78pwmf1.jpeg?auto=webp&s=f707069bd41611b6949fbcbb60708f5c0330f27e",
    movie: "https://drive.google.com/file/d/1lj_1bQM62XxUqEG9_taRrZcnaGg9cldN/preview",
    post : "https://i.redd.it/miraculous-ladybug-london-special-what-side-are-you-on-v0-1zclp7pwp9pd1.jpg?width=1851&format=pjpg&auto=webp&s=e5d35522b0d9272fa6ec4bef6f58b4f1714a949a"
  },
  {
    id: "miraculous-world5",
    title: "Proximamente (2026): Miraculous World Tokio: Fuerza Estelar",
    year: 2025,
    duration: "52min",
    rating: "TV-G",
    genres: ["Animación", "Aventura","Infantil","Acción","Fantasía"],
    description:"Cuando Ladybug viaja a Tokio, conoce a Miki y Kazuno, viejos amigos de Kagami, miembros de la Stellar Force, un equipo japonés de superhéroes. Juntos, unen fuerzas para detener a un nuevo supervillano que busca sembrar el caos en la ciudad.",
    trailerUrl: sampleTrailer,
    image: "https://static.wikia.nocookie.net/miraculousladybug/images/6/65/Miraculous_Tokio_Poster_2.png/revision/latest/scale-to-width/360?cb=20251006162713&path-prefix=es",
    post : "https://pbs.twimg.com/media/G4p_EKcW8AAWPM6.jpg",
    movie: "aun no"
  },
  {
    id: "miraculous-awakening",
    title: "Miraculous Awakenig",
    year: 2023,
    duration: "1h 39min",
    rating: "PG-",
    genres: ["Animación", "Aventura", "Romance","Infantil","Músical"],
    description:"Un guardián de joyas mágicas convierte a una chica peculiar y a un chico popular en superhéroes. No obstante, jamás podrán revelar su verdadera identidad, ni siquiera el uno al otro.",
    trailerUrl: "trailers/miraculous-awakening.mp4",
    image: "https://preview.redd.it/predictions-hopes-for-the-miraculous-awakening-sequels-v0-i9xn116q7jtb1.jpg?width=640&crop=smart&auto=webp&s=282d8dd69dbe6cce784798e6029b62fb3ca7fbfa",
    post: "https://miraculous.to/global_data/img/S0E03_2025-08-18_17-38-16.webp",
    movie: "https://drive.google.com/file/d/1LxopTMByDv1hArzUF0mnjodfHOoHJx4h/preview"
  },
  {
    id: "sonic-the-hedgehog",
    title: "Sonic",
    year: 2020,
    duration: "1h 39min",
    rating: "PG-13",
    genres: ["Infantil","Comedia"],
    description:"Sonic intenta atravesar las complejidades de la vida en la Tierra con su nuevo mejor amigo, un humano llamado Tom Wachowski. Deberán unir sus fuerzas para evitar que el malvado Dr. Robotnik capture a Sonic y use sus poderes para dominar el mundo.",
    trailerUrl: "trailers/sonic-the-hedgehog.mp4",
    image: "images/sonic.jpeg",
    post: "posters/.jpg",
    movie: "https://drive.google.com/file/d/1aYLsDe1HnNSqVjS7v_tiT-ztdcG3z7eU/preview"
  },
  {
    id: "sonic-the-hedgehog-2",
    title: "Sonic 2",
    year: 2022,
    duration: "2h 2min",
    rating: "PG",
    genres: ["Infantil","Acción"],
    description:"Después de establecerse en Green Hills, Sonic quiere demostrar que tiene la madures de ser héroe. La prueba de fuego llega con el retorno del malvado Robotnik, y su nuevo compinche, Knuckles, en busca de una esmeralda que destruye civilizaciones. Sonic forma equipo con su propio compañero de fatigas, Tails, y juntos se lanzan a una aventura que les llevará por todo el mundo en busca de la preciada piedra para evitar que caiga en manos equivocadas.",
    trailerUrl: sampleTrailer,
    image: "images/sonic2.jpeg",
    post: "posters/.jpg",
    movie: "https://drive.google.com/file/d/1F6fK3gCNh5afr7ARKLWIRgvZ6iyUWnko/preview"
  },
  {
    id: "sonic-the-hedgehog-3",
    title: "Sonic 3: Próximamente",
    year: 2022,
    duration: "2h 2min",
    rating: "PG",
    genres: ["Infantil","Acción"],
    description:"Después de establecerse en Green Hills, Sonic quiere demostrar que tiene la madures de ser héroe. La prueba de fuego llega con el retorno del malvado Robotnik, y su nuevo compinche, Knuckles, en busca de una esmeralda que destruye civilizaciones. Sonic forma equipo con su propio compañero de fatigas, Tails, y juntos se lanzan a una aventura que les llevará por todo el mundo en busca de la preciada piedra para evitar que caiga en manos equivocadas.",
    trailerUrl: sampleTrailer,
    image: "images/sonic3.jpeg",
    post: "posters/.jpg",
    movie: "preview"
  },
  {
    id: "five-nights-at-freddys",
    title: "Five Nights At Freddy's",
    year: 2023,
    duration: "1h 50min",
    rating: "PG-13",
    genres: ["Terror","Misterio"],
    description:"Mike Schmidt, un guardia de seguridad con problemas que empieza a trabajar en el turno de noche de la abandonada pizzería Freddy Fazbear's Pizza. A medida que pasa sus noches en el trabajo, descubre que las mascotas animatrónicas del lugar cobran vida de manera aterradora, lo que lleva a situaciones de suspense y terror. La trama explora el oscuro secreto de la pizzería, donde los animatrónicos están poseídos por las almas de niños secuestrados.",
    trailerUrl: "trailers/five-nights-at-freddys.mp4",
    image: "images/fnaf.jpg",
    movie: "https://drive.google.com/file/d/1NTEnMppzmWsNF0ufujXQp_6tr9i09JPF/preview"
  },
  {
    id: "five-nights-at-freddys2",
    title: "Five Nights At Freddy's 2: Próximamente",
    year: 2026,
    duration: "1h 50min",
    rating: "PG-13",
    genres: ["Terror","Misterio"],
    description:"Mike Schmidt, un guardia de seguridad con problemas que empieza a trabajar en el turno de noche de la abandonada pizzería Freddy Fazbear's Pizza. A medida que pasa sus noches en el trabajo, descubre que las mascotas animatrónicas del lugar cobran vida de manera aterradora, lo que lleva a situaciones de suspense y terror. La trama explora el oscuro secreto de la pizzería, donde los animatrónicos están poseídos por las almas de niños secuestrados.",
    trailerUrl: "trailers/five-nights-at-freddys2.mp4",
    image: "images/fnaf2.jpg",
    post: "posters/.jpg",
    movie: "https://drive.google.com/file/d/1NTEnMppzmWsNF0ufujXQp_6tr9i09JPF/preview"
  },
  {
    id: "five-nights-at-freddys3",
    title: "Five Nights At Freddy's 3: Próximamente",
    year: 2029,
    duration: "1h 50min",
    rating: "PG-13",
    genres: ["Terror","Misterio"],
    description:"Mike Schmidt, un guardia de seguridad con problemas que empieza a trabajar en el turno de noche de la abandonada pizzería Freddy Fazbear's Pizza. A medida que pasa sus noches en el trabajo, descubre que las mascotas animatrónicas del lugar cobran vida de manera aterradora, lo que lleva a situaciones de suspense y terror. La trama explora el oscuro secreto de la pizzería, donde los animatrónicos están poseídos por las almas de niños secuestrados.",
    trailerUrl: sampleTrailer,
    image: "images/five-nights-at-freddys-3-movie-poster-fan-made-by-me-model-v0-jv59k3jszvmf1.webp",
    post: "posters/.jpg",
    movie: "https://drive.google.com/file/d/1NTEnMppzmWsNF0ufujXQp_6tr9i09JPF/preview"
  },
  {
    id: "five-nights-at-freddys4",
    title: "Five Nights At Freddy's 4: Próximamente",
    year: 2035,
    duration: "1h 50min",
    rating: "PG-13",
    genres: ["Terror","Misterio"],
    description:"Mike Schmidt, un guardia de seguridad con problemas que empieza a trabajar en el turno de noche de la abandonada pizzería Freddy Fazbear's Pizza. A medida que pasa sus noches en el trabajo, descubre que las mascotas animatrónicas del lugar cobran vida de manera aterradora, lo que lleva a situaciones de suspense y terror. La trama explora el oscuro secreto de la pizzería, donde los animatrónicos están poseídos por las almas de niños secuestrados.",
    trailerUrl: sampleTrailer,
    image: "images/@fredbearfilms.jpg",
    post: "posters/.jpg",
    movie: "https://drive.google.com/file/d/1NTEnMppzmWsNF0ufujXQp_6tr9i09JPF/preview"
  },
  {
    id: "logan-wolverine",
    title: "Logan - Wolverine",
    year: 2017,
    duration: "2h 17min",
    rating: "PG-13",
    genres: ["Animación", "Ciencia Ficción", "Superhéroes"],
    description:"En un futuro cercano donde los mutantes están casi extintos, un cansado y envejecido Logan, cuyos poderes curativos están disminuyendo, se gana la vida como conductor de limusinas y cuida a un Profesor X enfermo y debilitado. Su vida cambia drásticamente cuando una mujer le pide que proteja a una joven mutante llamada Laura, quien es perseguida por fuerzas oscuras y posee poderes similares a los de él. Juntos, Logan, Charles y Laura emprenden un viaje para llevar a la niña a un refugio seguro llamado «Edén», enfrentándose a una peligrosa conspiración mientras Logan busca la redención.",
    trailerUrl: sampleTrailer,
    image: "images/logan-wolverine.jpg",
    post: "posters/.jpg",
    movie: "https://drive.google.com/file/d/11LZONN67ENZ7vo7wPpIPg2c6K4RzqLqW/preview"
  },
  {
    id: "deadpool",
    title: "DeadPool",
    year: 2024,
    duration: "2h 08min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Wade Wilson (Deadpool) abandona su retiro para unirse a una versión alterna de Wolverine, con el objetivo de salvar el multiverso de una amenaza externa. La historia comienza cuando la Autoridad de Variación Temporal (TVA) interrumpe la vida de Wade, llevándolo a una misión para enfrentar una crisis que podría borrar su universo de la existencia.",
    trailerUrl: sampleTrailer,
    image: "images/deadpool.png",
    post: "posters/.jpg",
    movie: "https://drive.google.com/file/d/1w9pPohiLbkp3GTjTJNqPsh60khrX68Ab/preview"
  },
  {
    id: "deadpool2",
    title: "DeadPool 2",
    year: 2024,
    duration: "2h 08min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Wade Wilson (Deadpool) abandona su retiro para unirse a una versión alterna de Wolverine, con el objetivo de salvar el multiverso de una amenaza externa. La historia comienza cuando la Autoridad de Variación Temporal (TVA) interrumpe la vida de Wade, llevándolo a una misión para enfrentar una crisis que podría borrar su universo de la existencia.",
    trailerUrl: sampleTrailer,
    image: "images/deadpool2.jpg",
    movie: "https://drive.google.com/file/d/1w9pPohiLbkp3GTjTJNqPsh60khrX68Ab/preview"
  },
  {
    id: "deadpool3",
    title: "DeadPool 3",
    year: 2024,
    duration: "2h 08min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Wade Wilson (Deadpool) abandona su retiro para unirse a una versión alterna de Wolverine, con el objetivo de salvar el multiverso de una amenaza externa. La historia comienza cuando la Autoridad de Variación Temporal (TVA) interrumpe la vida de Wade, llevándolo a una misión para enfrentar una crisis que podría borrar su universo de la existencia.",
    trailerUrl: sampleTrailer,
    image: "images/deadpool3.jpg",
    movie: "https://drive.google.com/file/d/1w9pPohiLbkp3GTjTJNqPsh60khrX68Ab/preview"
  },
  {
    id: "tinkerbel",
    title: "TinkerBell",
    year: 2008,
    duration: "1h 23min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Viaja al secreto mundo de Pixie Hollow y escucha cantar a Tinker Bell mientras se revela la historia de la famosa hada de Disney. ¿Te preguntaste cómo surge el brillo de la naturaleza? ¿Quién le da luz y color entre las estaciones? Tinker Bell y sus cuatro mejores amigas hadas convierten el invierno en primavera y aprenden la importancia de ser fiel a uno mismo.",
    trailerUrl: sampleTrailer,
    image: "images/tinkerbell.jpg",
    movie: "https://drive.google.com/file/d/15hdvpjmUCJ9kNnUfOn5JOuVqLpQiVkR4/preview"
  },
  {
    id: "tinkerbel2",
    title: "TinkerBell 2: EL Tesoro Perdido",
    year: 2009,
    duration: "1h 25min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Saldrá una luna cosecha azul, y las hadas utilizarán una piedra lunar para restaurar el Árbol del Polvillo de Hadas, la fuente de su magia. Pero cuando Tinker Bell pone en riesgo todo Pixie Hollow, deberá aventurarse por el mar en una búsqueda para arreglar las cosas. Con su amigo Terence y la luciérnaga encantadora y pícara Blaze, Tink se enfrentará a un nuevo mundo y descubrirá el mejor tesoro.",
    trailerUrl: sampleTrailer,
    image: "images/tinkerbell2.jpg",
    movie: "https://drive.google.com/file/d/1iL5GrlinMujHqedzyQU0ebS7gVaSCkPP/preview"
  },
  {
    id: "tinkerbel3",
    title: "TinkerBell 3: Hadas al Rescate",
    year: 2010,
    duration: "1h 16min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Antes de conocer a Wendy y los Niños Perdidos, Tinker Bell conoció a Lizzy, una niña que cree en las hadas. En la campiña se da un encuentro cuando Tink es descubierta por Lizzy. Sus mundos se unen y Tink desarrolla un lazo con la niña curiosa que necesita una amiga. Sus hadas compañeras lanzan un audaz rescate, y Tinker Bell pone en riesgo su seguridad y el futuro de las hadas.",
    trailerUrl: sampleTrailer,
    image: "images/tinkerbell3.jpg",
    movie: "https://drive.google.com/file/d/1shBNCAb3QkavzXx7PKbe8HLahWQo7fCt/preview"
  },
  {
    id: "tinkerbel4",
    title: "TinkerBell 4: El Secreto de las Hadas",
    year: 2012,
    duration: "1h 15min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Una misteriosa fuerza atrae a Tink para cruzar la frontera hacia el desconocido mundo de los Bosques de Invierno, un lugar donde las hadas de Pixie Hollow tienen prohibido ir. Allí descubre un secreto que cambiará su vida para siempre: tiene una hermana llamada Periwinkle. Cuando Pixie Hollow se ve amenazado, el dúo debe trabajar unido para salvar ambos mundos.",
    trailerUrl: sampleTrailer,
    image: "images/tinkerbell4.jpg",
    movie: "https://drive.google.com/file/d/1FbnSkyTL26eRGxc-PZGHgQLz7Kqpa0GB/preview"
  },
  {
    id: "tinkerbel5",
    title: "TinkerBell 5: La Hada Pirata",
    year: 2014,
    duration: "1h 30min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"Desde el mundo de Peter Pan, llega una aventura sobre Zarina, un hada inteligente y ambiciosa cautivada por el polvillo de hada azul y sus infinitas posibilidades. Cuando las ideas salvajes de Zarina la meten en problemas, huye de la tierra de las hadas y se une a los piratas intrigantes de Skull Rock. Tinker Bell y sus amigos deben encontrar a Zarina, y luchan contra la banda de piratas liderada por un grumete llamado James, quien pronto se hará conocido como el propio capitán Garfio.",
    trailerUrl: sampleTrailer,
    image: "images/tinkerbell5.jpg",
    movie: "https://drive.google.com/file/d/1TYB_T6hH39nAcvvpARykmTiNOdw2rKAQ/preview"
  },
  {
    id: "tinkerbel6",
    title: "TinkerBell 6: La Leyenda de la Bestia de Nunca Jamás",
    year: 2014,
    duration: "1h 16min",
    rating: "PG-13",
    genres: ["Comedia", "Acción"],
    description:"El antiguo mito de una criatura legendaria, la Bestia de Nunca Jamás, provoca curiosidad en Tinker Bell y su amiga Fawn, un hada de los animales que romperá las reglas para ayudar a cualquier animal que lo necesite. Pero esta criatura no es bienvenida en la Tierra de las Hadas, y las hadas exploradoras pretenden capturarla. Fawn, que ve un corazón tierno bajo su hosco exterior, deberá convencer a sus amigas de rescatar a la Bestia de Nunca Jamás. Algunas secuencias o patrones de luces intermitentes pueden afectar a espectadores fotosensibles.",
    trailerUrl: sampleTrailer,
    image: "images/tinkerbell6.jpg",
    movie: "https://drive.google.com/file/d/1gj_AJBWsrdK17wGRb0TX9q2ntOmY8F2l/preview"
  },
  {
    id: "finding-nemo",
    title: "Buscando a Nemo",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/finding-nemo.jpeg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "finding-dory-2016",
    title: "Buscando a Dory",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/finding-dory.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "anaconda-el-despertar",
    title: "Anaconda El Despertar",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/anaconda-el-despertar.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "oni-goroshi",
    title: "Oni Goroshi - La Ciudad de los Demonios",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/oni-goroshi.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "a_minecraft-movie",
    title: "Una Pelicula de Minecraft",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/a_minecraft-movie.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "truman-show",
    title: "El Show de Truman",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/truman-show.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "apocalypto",
    title: "Apocalipto",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/apocalypto.jpg",
    movie: "C:/xampp/htdocs/ShareFilms4.PeliculasGratis/pelis/Apocalypto.mp4"
  },
  {
    id: "bright-burn",
    title: "El Hijo de la Oscuridad",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/bright-burn.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "shrek",
    title: "Shrek",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/shrek.jpg",
    movie: ""
  },
  {
    id: "shrek-2",
    title: "Shrek 2",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/shrek-2.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "shrek-3",
    title: "Shrek 3",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/shrek-3.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "shrek-4",
    title: "Shrek 4",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/shrek-4.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "The_Gangster_The_Cop_The_Devil",
    title: "El Gangster, El Policía y El Diablo",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/The_Gangster_The_Cop_The_Devil.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "destino-final-lazos-de-sangre",
    title: "Destino Final - Lazos de Sangre",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/destino-final-lazos-de-sangre.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "captain-america",
    title: "Capitan America - El Primer Vengador",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/captain-america.webp",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "captain-america2",
    title: "Capitan America 2 - El Soldado del Invierno",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/captain-america2.jpg",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  },
  {
    id: "captain-america3",
    title: "Capitan America 3 - Civil War",
    year: 2016,
    duration: "1h 37min",
    rating: "PG-13",
    genres: ["Acción", "Aventura","Comedia","Animación"],
    description:"Cuando Dory, la olvidadiza pez cirujano, recuerda que tiene una familia que podría estar buscándola, va en una aventura con Marlin y Nemo para encontrarla con ayuda de Hank, un pulpo gruñón, Bailey, una beluga convencida de que sus sonar biológico anda mal, y Destiny, una tiburón ballena miope.",
    trailerUrl: sampleTrailer,
    image: "images/captain-america3.webp",
    movie: "https://drive.google.com/file/d/1x5il-6bRAx6IGrwWnZlNrNwbc-GW16WK/preview"
  }
];

// (Opcional) Exponerlo globalmente
window.MOVIES = MOVIES; 